Document: cometd-twisted
Title: Debian cometd-twisted Manual
Author: <insert document author here>
Abstract: This manual describes what cometd-twisted is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cometd-twisted/cometd-twisted.sgml.gz

Format: postscript
Files: /usr/share/doc/cometd-twisted/cometd-twisted.ps.gz

Format: text
Files: /usr/share/doc/cometd-twisted/cometd-twisted.text.gz

Format: HTML
Index: /usr/share/doc/cometd-twisted/html/index.html
Files: /usr/share/doc/cometd-twisted/html/*.html
